[phases.setup]
  nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
  cmd = "npm install"

[phases.build]
  cmd = "npm run build"

[phases.start]
  cmd = "node dist/server.js"

[variables]
  NODE_ENV = "production"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"